apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
  #label:
    #app: db2schema
spec:
  template:
    metadata:
      name: db2-setup-pod
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Never
      containers:
        - name: db2-setup-pod
          image: quay.io/ibmgaragecloud/alpine-curl
          volumeMounts:
            - mountPath: /db2scripts
              name: db2scripts
          env:
            - name: ENV_USERNAME
              value: "admin"
            - name: ENV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user-details
                  key: initial_admin_password
            - name: InstanceNamespace
              value: {{ .Values.namespace }} 
            - name: InstanceSecret
              value: {{ .Values.InstanceSecret }}
            - name: database-name
              value: {{ .Values.database_name }}
            - name: storageclassname
              value: {{ .Values.storageClassName }}
            - name: InstanceType
              value: {{ .Values.InstanceType }}
            - name: InstanceVersion
              value:  {{ .Values.InstanceVersion }}
            - name: InstanceId
              value:  {{ .Values.InstanceId | quote }}
            - name: CPDClusterHost
              value:  {{ .Values.CPDClusterHost }}
            - name: DatabaseHost
              value:  {{ .Values.DatabaseHost }}
          command:
            - /bin/sh
          args:
            - '-c'
            - cat /db2scripts/cp_db2_setup.sh && ls -l /db2scripts/ && /db2scripts/cp_db2_setup.sh
      volumes:
        - name: db2scripts
          configMap:
            name: {{ .Values.ConfigmapName }}
            defaultMode: 0777
